# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowGUI.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 495)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtWidgets.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.widget.setObjectName("widget")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_30.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_30.addWidget(self.label, 0, 0, 1, 1)
        self.storyNumberComboBox = QtWidgets.QComboBox(self.widget)
        self.storyNumberComboBox.setObjectName("storyNumberComboBox")
        self.storyNumberComboBox.addItem("")
        self.gridLayout_30.addWidget(self.storyNumberComboBox, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_30.addWidget(self.label_2, 1, 0, 1, 1)
        self.storyMassLineEdit = QtWidgets.QLineEdit(self.widget)
        self.storyMassLineEdit.setObjectName("storyMassLineEdit")
        self.gridLayout_30.addWidget(self.storyMassLineEdit, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_30.addWidget(self.label_3, 2, 0, 1, 1)
        self.storyHeightLineEdit = QtWidgets.QLineEdit(self.widget)
        self.storyHeightLineEdit.setObjectName("storyHeightLineEdit")
        self.gridLayout_30.addWidget(self.storyHeightLineEdit, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_30.addWidget(self.label_4, 3, 0, 1, 1)
        self.columnWidthLineEdit = QtWidgets.QLineEdit(self.widget)
        self.columnWidthLineEdit.setObjectName("columnWidthLineEdit")
        self.gridLayout_30.addWidget(self.columnWidthLineEdit, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_30.addWidget(self.label_5, 4, 0, 1, 1)
        self.columnDepthLineEdit = QtWidgets.QLineEdit(self.widget)
        self.columnDepthLineEdit.setObjectName("columnDepthLineEdit")
        self.gridLayout_30.addWidget(self.columnDepthLineEdit, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_30.addWidget(self.label_6, 5, 0, 1, 1)
        self.elasticityModuleLineEdit = QtWidgets.QLineEdit(self.widget)
        self.elasticityModuleLineEdit.setObjectName("elasticityModuleLineEdit")
        self.gridLayout_30.addWidget(self.elasticityModuleLineEdit, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_30.addWidget(self.label_7, 6, 0, 1, 1)
        self.supportTypeComboBox = QtWidgets.QComboBox(self.widget)
        self.supportTypeComboBox.setObjectName("supportTypeComboBox")
        self.supportTypeComboBox.addItem("")
        self.supportTypeComboBox.addItem("")
        self.supportTypeComboBox.addItem("")
        self.supportTypeComboBox.addItem("")
        self.gridLayout_30.addWidget(self.supportTypeComboBox, 6, 1, 1, 1)
        self.addStoryBtn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addStoryBtn.sizePolicy().hasHeightForWidth())
        self.addStoryBtn.setSizePolicy(sizePolicy)
        self.addStoryBtn.setObjectName("addStoryBtn")
        self.gridLayout_30.addWidget(self.addStoryBtn, 7, 0, 1, 2)
        self.removeStoryBtn = QtWidgets.QPushButton(self.widget)
        self.removeStoryBtn.setObjectName("removeStoryBtn")
        self.gridLayout_30.addWidget(self.removeStoryBtn, 8, 0, 1, 2)
        self.storyNumberComboBox.raise_()
        self.addStoryBtn.raise_()
        self.removeStoryBtn.raise_()
        self.label_3.raise_()
        self.storyMassLineEdit.raise_()
        self.label.raise_()
        self.columnWidthLineEdit.raise_()
        self.label_2.raise_()
        self.supportTypeComboBox.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.elasticityModuleLineEdit.raise_()
        self.columnDepthLineEdit.raise_()
        self.storyHeightLineEdit.raise_()
        self.label_7.raise_()
        self.label_5.raise_()
        self.structureWidget = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.structureWidget.sizePolicy().hasHeightForWidth())
        self.structureWidget.setSizePolicy(sizePolicy)
        self.structureWidget.setObjectName("structureWidget")
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.splitter_2 = QtWidgets.QSplitter(self.tab_2)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.widget_2 = QtWidgets.QWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.confirmTlcdBtn = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirmTlcdBtn.sizePolicy().hasHeightForWidth())
        self.confirmTlcdBtn.setSizePolicy(sizePolicy)
        self.confirmTlcdBtn.setObjectName("confirmTlcdBtn")
        self.gridLayout_4.addWidget(self.confirmTlcdBtn, 2, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.tlcdModelComboBox = QtWidgets.QComboBox(self.widget_2)
        self.tlcdModelComboBox.setObjectName("tlcdModelComboBox")
        self.tlcdModelComboBox.addItem("")
        self.tlcdModelComboBox.addItem("")
        self.tlcdModelComboBox.addItem("")
        self.gridLayout_4.addWidget(self.tlcdModelComboBox, 0, 1, 1, 1)
        self.tlcdStackedWidget = QtWidgets.QStackedWidget(self.widget_2)
        self.tlcdStackedWidget.setObjectName("tlcdStackedWidget")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_9 = QtWidgets.QLabel(self.page_5)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.tlcdStackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_12 = QtWidgets.QLabel(self.page_6)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 2, 0, 1, 1)
        self.diameterSimpleTlcdLineEdit = QtWidgets.QLineEdit(self.page_6)
        self.diameterSimpleTlcdLineEdit.setObjectName("diameterSimpleTlcdLineEdit")
        self.gridLayout_6.addWidget(self.diameterSimpleTlcdLineEdit, 0, 1, 1, 1)
        self.widthSimpleTlcdLineEdit = QtWidgets.QLineEdit(self.page_6)
        self.widthSimpleTlcdLineEdit.setObjectName("widthSimpleTlcdLineEdit")
        self.gridLayout_6.addWidget(self.widthSimpleTlcdLineEdit, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.page_6)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.page_6)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 1, 0, 1, 1)
        self.waterLevelSimpleTlcdLineEdit = QtWidgets.QLineEdit(self.page_6)
        self.waterLevelSimpleTlcdLineEdit.setObjectName("waterLevelSimpleTlcdLineEdit")
        self.gridLayout_6.addWidget(self.waterLevelSimpleTlcdLineEdit, 1, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.page_6)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 3, 0, 1, 1)
        self.amountSimpleTlcdLineEdit = QtWidgets.QLineEdit(self.page_6)
        self.amountSimpleTlcdLineEdit.setObjectName("amountSimpleTlcdLineEdit")
        self.gridLayout_6.addWidget(self.amountSimpleTlcdLineEdit, 3, 1, 1, 1)
        self.tlcdStackedWidget.addWidget(self.page_6)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.diameterPressureTlcdLineEdit = QtWidgets.QLineEdit(self.page)
        self.diameterPressureTlcdLineEdit.setObjectName("diameterPressureTlcdLineEdit")
        self.gridLayout_2.addWidget(self.diameterPressureTlcdLineEdit, 0, 1, 1, 2)
        self.label_19 = QtWidgets.QLabel(self.page)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.page)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 1, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.page)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 3, 0, 1, 2)
        self.waterLevelPressureTlcdLineEdit = QtWidgets.QLineEdit(self.page)
        self.waterLevelPressureTlcdLineEdit.setObjectName("waterLevelPressureTlcdLineEdit")
        self.gridLayout_2.addWidget(self.waterLevelPressureTlcdLineEdit, 1, 1, 1, 2)
        self.widthPressureTlcdLineEdit = QtWidgets.QLineEdit(self.page)
        self.widthPressureTlcdLineEdit.setObjectName("widthPressureTlcdLineEdit")
        self.gridLayout_2.addWidget(self.widthPressureTlcdLineEdit, 2, 1, 1, 2)
        self.label_21 = QtWidgets.QLabel(self.page)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 2, 0, 1, 1)
        self.gasHeightPressureTlcdLineEdit = QtWidgets.QLineEdit(self.page)
        self.gasHeightPressureTlcdLineEdit.setObjectName("gasHeightPressureTlcdLineEdit")
        self.gridLayout_2.addWidget(self.gasHeightPressureTlcdLineEdit, 3, 2, 1, 1)
        self.gasPressurePressureTlcdLineEdit = QtWidgets.QLineEdit(self.page)
        self.gasPressurePressureTlcdLineEdit.setObjectName("gasPressurePressureTlcdLineEdit")
        self.gridLayout_2.addWidget(self.gasPressurePressureTlcdLineEdit, 4, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.page)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 4, 0, 1, 2)
        self.label_26 = QtWidgets.QLabel(self.page)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 5, 0, 1, 1)
        self.amountPressureTlcdLineEdit = QtWidgets.QLineEdit(self.page)
        self.amountPressureTlcdLineEdit.setObjectName("amountPressureTlcdLineEdit")
        self.gridLayout_2.addWidget(self.amountPressureTlcdLineEdit, 5, 2, 1, 1)
        self.tlcdStackedWidget.addWidget(self.page)
        self.gridLayout_4.addWidget(self.tlcdStackedWidget, 1, 0, 1, 2)
        self.tlcdModelComboBox.raise_()
        self.tlcdStackedWidget.raise_()
        self.confirmTlcdBtn.raise_()
        self.label_8.raise_()
        self.tlcdWidget = QtWidgets.QWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tlcdWidget.sizePolicy().hasHeightForWidth())
        self.tlcdWidget.setSizePolicy(sizePolicy)
        self.tlcdWidget.setObjectName("tlcdWidget")
        self.gridLayout_7.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.splitter_3 = QtWidgets.QSplitter(self.tab_3)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.widget_3 = QtWidgets.QWidget(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.excitationTypeComboBox = QtWidgets.QComboBox(self.widget_3)
        self.excitationTypeComboBox.setObjectName("excitationTypeComboBox")
        self.excitationTypeComboBox.addItem("")
        self.excitationTypeComboBox.addItem("")
        self.gridLayout_8.addWidget(self.excitationTypeComboBox, 0, 1, 1, 1)
        self.confirmExcitationButton = QtWidgets.QPushButton(self.widget_3)
        self.confirmExcitationButton.setObjectName("confirmExcitationButton")
        self.gridLayout_8.addWidget(self.confirmExcitationButton, 2, 0, 1, 2)
        self.excitationStackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.excitationStackedWidget.setObjectName("excitationStackedWidget")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_14 = QtWidgets.QLabel(self.page_7)
        self.label_14.setObjectName("label_14")
        self.gridLayout_10.addWidget(self.label_14, 0, 0, 1, 1)
        self.sineAmplitudeLineEdit = QtWidgets.QLineEdit(self.page_7)
        self.sineAmplitudeLineEdit.setObjectName("sineAmplitudeLineEdit")
        self.gridLayout_10.addWidget(self.sineAmplitudeLineEdit, 0, 1, 1, 1)
        self.sineFrequencyLabel = QtWidgets.QLabel(self.page_7)
        self.sineFrequencyLabel.setObjectName("sineFrequencyLabel")
        self.gridLayout_10.addWidget(self.sineFrequencyLabel, 1, 0, 1, 1)
        self.sineFrequencyLineEdit = QtWidgets.QLineEdit(self.page_7)
        self.sineFrequencyLineEdit.setObjectName("sineFrequencyLineEdit")
        self.gridLayout_10.addWidget(self.sineFrequencyLineEdit, 1, 1, 1, 1)
        self.sineFrequencyRatioCheckBox = QtWidgets.QCheckBox(self.page_7)
        self.sineFrequencyRatioCheckBox.setChecked(False)
        self.sineFrequencyRatioCheckBox.setObjectName("sineFrequencyRatioCheckBox")
        self.gridLayout_10.addWidget(self.sineFrequencyRatioCheckBox, 1, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.page_7)
        self.label_16.setObjectName("label_16")
        self.gridLayout_10.addWidget(self.label_16, 2, 0, 1, 1)
        self.sineExcitationDurationLineEdit = QtWidgets.QLineEdit(self.page_7)
        self.sineExcitationDurationLineEdit.setObjectName("sineExcitationDurationLineEdit")
        self.gridLayout_10.addWidget(self.sineExcitationDurationLineEdit, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.page_7)
        self.label_17.setObjectName("label_17")
        self.gridLayout_10.addWidget(self.label_17, 3, 0, 1, 1)
        self.sineAnalysisDurationLineEdit = QtWidgets.QLineEdit(self.page_7)
        self.sineAnalysisDurationLineEdit.setObjectName("sineAnalysisDurationLineEdit")
        self.gridLayout_10.addWidget(self.sineAnalysisDurationLineEdit, 3, 1, 1, 1)
        self.excitationStackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page_8)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.importExcitationButton = QtWidgets.QPushButton(self.page_8)
        self.importExcitationButton.setObjectName("importExcitationButton")
        self.gridLayout_12.addWidget(self.importExcitationButton, 1, 0, 1, 1)
        self.generateExcitationButton = QtWidgets.QPushButton(self.page_8)
        self.generateExcitationButton.setObjectName("generateExcitationButton")
        self.gridLayout_12.addWidget(self.generateExcitationButton, 1, 1, 1, 1)
        self.excitationFileLineEdit = QtWidgets.QLineEdit(self.page_8)
        self.excitationFileLineEdit.setObjectName("excitationFileLineEdit")
        self.gridLayout_12.addWidget(self.excitationFileLineEdit, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.page_8)
        self.label_18.setObjectName("label_18")
        self.gridLayout_12.addWidget(self.label_18, 0, 0, 1, 1)
        self.excitationStackedWidget.addWidget(self.page_8)
        self.gridLayout_8.addWidget(self.excitationStackedWidget, 1, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.widget_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 0, 0, 1, 1)
        self.excitationWidget = QtWidgets.QWidget(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.excitationWidget.sizePolicy().hasHeightForWidth())
        self.excitationWidget.setSizePolicy(sizePolicy)
        self.excitationWidget.setObjectName("excitationWidget")
        self.gridLayout_9.addWidget(self.splitter_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.reportTextBrowser = QtWidgets.QTextBrowser(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.reportTextBrowser.setFont(font)
        self.reportTextBrowser.setObjectName("reportTextBrowser")
        self.gridLayout_16.addWidget(self.reportTextBrowser, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.splitter_4 = QtWidgets.QSplitter(self.tab_5)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.widget_4 = QtWidgets.QWidget(self.splitter_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox = QtWidgets.QGroupBox(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.list1 = QtWidgets.QListWidget(self.groupBox)
        self.list1.setObjectName("list1")
        self.gridLayout_14.addWidget(self.list1, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox, 0, 0, 3, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.list2 = QtWidgets.QListWidget(self.groupBox_2)
        self.list2.setObjectName("list2")
        self.gridLayout_15.addWidget(self.list2, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_2, 0, 3, 3, 1)
        self.addToPlotButton = QtWidgets.QPushButton(self.widget_4)
        self.addToPlotButton.setObjectName("addToPlotButton")
        self.gridLayout_11.addWidget(self.addToPlotButton, 0, 2, 1, 1)
        self.removeFromPlotButton = QtWidgets.QPushButton(self.widget_4)
        self.removeFromPlotButton.setObjectName("removeFromPlotButton")
        self.gridLayout_11.addWidget(self.removeFromPlotButton, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem, 2, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.widget_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_11.addWidget(self.label_20, 3, 0, 1, 1)
        self.plotButton = QtWidgets.QPushButton(self.widget_4)
        self.plotButton.setObjectName("plotButton")
        self.gridLayout_11.addWidget(self.plotButton, 3, 3, 1, 1)
        self.plotTypeComboBox = QtWidgets.QComboBox(self.widget_4)
        self.plotTypeComboBox.setObjectName("plotTypeComboBox")
        self.plotTypeComboBox.addItem("")
        self.plotTypeComboBox.addItem("")
        self.plotTypeComboBox.addItem("")
        self.plotTypeComboBox.addItem("")
        self.gridLayout_11.addWidget(self.plotTypeComboBox, 3, 1, 1, 1)
        self.dynRespWidget = QtWidgets.QWidget(self.splitter_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dynRespWidget.sizePolicy().hasHeightForWidth())
        self.dynRespWidget.setSizePolicy(sizePolicy)
        self.dynRespWidget.setObjectName("dynRespWidget")
        self.gridLayout_13.addWidget(self.splitter_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.splitter_5 = QtWidgets.QSplitter(self.tab_6)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.widget_5 = QtWidgets.QWidget(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.dmfProgressBar = QtWidgets.QProgressBar(self.widget_5)
        self.dmfProgressBar.setProperty("value", 0)
        self.dmfProgressBar.setObjectName("dmfProgressBar")
        self.gridLayout_17.addWidget(self.dmfProgressBar, 0, 0, 1, 4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.list3 = QtWidgets.QListWidget(self.groupBox_3)
        self.list3.setObjectName("list3")
        self.gridLayout_19.addWidget(self.list3, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_3, 1, 0, 3, 2)
        self.addToDMFPlot = QtWidgets.QPushButton(self.widget_5)
        self.addToDMFPlot.setObjectName("addToDMFPlot")
        self.gridLayout_17.addWidget(self.addToDMFPlot, 1, 2, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.list4 = QtWidgets.QListWidget(self.groupBox_4)
        self.list4.setObjectName("list4")
        self.gridLayout_20.addWidget(self.list4, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_4, 1, 3, 3, 1)
        self.removeFromDMFPlot = QtWidgets.QPushButton(self.widget_5)
        self.removeFromDMFPlot.setObjectName("removeFromDMFPlot")
        self.gridLayout_17.addWidget(self.removeFromDMFPlot, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem1, 3, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.gridLayout_17.addWidget(self.label_15, 4, 0, 1, 1)
        self.dmfPlotTypeComboBox = QtWidgets.QComboBox(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dmfPlotTypeComboBox.sizePolicy().hasHeightForWidth())
        self.dmfPlotTypeComboBox.setSizePolicy(sizePolicy)
        self.dmfPlotTypeComboBox.setObjectName("dmfPlotTypeComboBox")
        self.dmfPlotTypeComboBox.addItem("")
        self.dmfPlotTypeComboBox.addItem("")
        self.gridLayout_17.addWidget(self.dmfPlotTypeComboBox, 4, 1, 1, 1)
        self.dmfPlotButton = QtWidgets.QPushButton(self.widget_5)
        self.dmfPlotButton.setObjectName("dmfPlotButton")
        self.gridLayout_17.addWidget(self.dmfPlotButton, 4, 3, 1, 1)
        self.dmfWidget = QtWidgets.QWidget(self.splitter_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dmfWidget.sizePolicy().hasHeightForWidth())
        self.dmfWidget.setSizePolicy(sizePolicy)
        self.dmfWidget.setObjectName("dmfWidget")
        self.gridLayout_18.addWidget(self.splitter_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 690, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuConfigurations = QtWidgets.QMenu(self.menubar)
        self.menuConfigurations.setObjectName("menuConfigurations")
        self.menuMethods = QtWidgets.QMenu(self.menuConfigurations)
        self.menuMethods.setObjectName("menuMethods")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuTheme = QtWidgets.QMenu(self.menuWindow)
        self.menuTheme.setObjectName("menuTheme")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNewFile = QtWidgets.QAction(MainWindow)
        self.actionNewFile.setObjectName("actionNewFile")
        self.actionOpenFile = QtWidgets.QAction(MainWindow)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.actionSaveFile = QtWidgets.QAction(MainWindow)
        self.actionSaveFile.setObjectName("actionSaveFile")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionExportReport = QtWidgets.QAction(MainWindow)
        self.actionExportReport.setObjectName("actionExportReport")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionFiniteDifferenceMethod = QtWidgets.QAction(MainWindow)
        self.actionFiniteDifferenceMethod.setCheckable(True)
        self.actionFiniteDifferenceMethod.setChecked(True)
        self.actionFiniteDifferenceMethod.setObjectName("actionFiniteDifferenceMethod")
        self.actionStepSize = QtWidgets.QAction(MainWindow)
        self.actionStepSize.setObjectName("actionStepSize")
        self.actionBoundaryConditions = QtWidgets.QAction(MainWindow)
        self.actionBoundaryConditions.setObjectName("actionBoundaryConditions")
        self.actionStructureDamping = QtWidgets.QAction(MainWindow)
        self.actionStructureDamping.setObjectName("actionStructureDamping")
        self.actionFluidParameters = QtWidgets.QAction(MainWindow)
        self.actionFluidParameters.setObjectName("actionFluidParameters")
        self.actionLinearAccelerationMethod = QtWidgets.QAction(MainWindow)
        self.actionLinearAccelerationMethod.setCheckable(True)
        self.actionLinearAccelerationMethod.setObjectName("actionLinearAccelerationMethod")
        self.actionRunDynamicResponse = QtWidgets.QAction(MainWindow)
        self.actionRunDynamicResponse.setObjectName("actionRunDynamicResponse")
        self.actionDynamicMagnificationFactor = QtWidgets.QAction(MainWindow)
        self.actionDynamicMagnificationFactor.setObjectName("actionDynamicMagnificationFactor")
        self.actionOptimization = QtWidgets.QAction(MainWindow)
        self.actionOptimization.setObjectName("actionOptimization")
        self.actionMaximize = QtWidgets.QAction(MainWindow)
        self.actionMaximize.setObjectName("actionMaximize")
        self.actionFullScreen = QtWidgets.QAction(MainWindow)
        self.actionFullScreen.setObjectName("actionFullScreen")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDevelopmentTool = QtWidgets.QAction(MainWindow)
        self.actionDevelopmentTool.setObjectName("actionDevelopmentTool")
        self.actionBasicWhite = QtWidgets.QAction(MainWindow)
        self.actionBasicWhite.setCheckable(True)
        self.actionBasicWhite.setChecked(True)
        self.actionBasicWhite.setObjectName("actionBasicWhite")
        self.actionDarkOrange = QtWidgets.QAction(MainWindow)
        self.actionDarkOrange.setCheckable(True)
        self.actionDarkOrange.setObjectName("actionDarkOrange")
        self.actionDarkGreen = QtWidgets.QAction(MainWindow)
        self.actionDarkGreen.setCheckable(True)
        self.actionDarkGreen.setObjectName("actionDarkGreen")
        self.actionAqua = QtWidgets.QAction(MainWindow)
        self.actionAqua.setCheckable(True)
        self.actionAqua.setObjectName("actionAqua")
        self.actionDarkBlue = QtWidgets.QAction(MainWindow)
        self.actionDarkBlue.setCheckable(True)
        self.actionDarkBlue.setObjectName("actionDarkBlue")
        self.actionDMFSettings = QtWidgets.QAction(MainWindow)
        self.actionDMFSettings.setObjectName("actionDMFSettings")
        self.actionDarcula = QtWidgets.QAction(MainWindow)
        self.actionDarcula.setCheckable(True)
        self.actionDarcula.setObjectName("actionDarcula")
        self.actionBlueGlass = QtWidgets.QAction(MainWindow)
        self.actionBlueGlass.setCheckable(True)
        self.actionBlueGlass.setObjectName("actionBlueGlass")
        self.actionDark = QtWidgets.QAction(MainWindow)
        self.actionDark.setCheckable(True)
        self.actionDark.setObjectName("actionDark")
        self.actionDarkBlueFreeCAD = QtWidgets.QAction(MainWindow)
        self.actionDarkBlueFreeCAD.setCheckable(True)
        self.actionDarkBlueFreeCAD.setObjectName("actionDarkBlueFreeCAD")
        self.actionDarkGreenFreeCAD = QtWidgets.QAction(MainWindow)
        self.actionDarkGreenFreeCAD.setCheckable(True)
        self.actionDarkGreenFreeCAD.setObjectName("actionDarkGreenFreeCAD")
        self.actionDarkOrangeFreeCAD = QtWidgets.QAction(MainWindow)
        self.actionDarkOrangeFreeCAD.setCheckable(True)
        self.actionDarkOrangeFreeCAD.setObjectName("actionDarkOrangeFreeCAD")
        self.actionLight = QtWidgets.QAction(MainWindow)
        self.actionLight.setCheckable(True)
        self.actionLight.setObjectName("actionLight")
        self.actionLightBlueFreeCAD = QtWidgets.QAction(MainWindow)
        self.actionLightBlueFreeCAD.setCheckable(True)
        self.actionLightBlueFreeCAD.setObjectName("actionLightBlueFreeCAD")
        self.actionLightGreenFreeCAD = QtWidgets.QAction(MainWindow)
        self.actionLightGreenFreeCAD.setCheckable(True)
        self.actionLightGreenFreeCAD.setObjectName("actionLightGreenFreeCAD")
        self.actionLightOrangeFreeCAD = QtWidgets.QAction(MainWindow)
        self.actionLightOrangeFreeCAD.setCheckable(True)
        self.actionLightOrangeFreeCAD.setObjectName("actionLightOrangeFreeCAD")
        self.actionMachinery = QtWidgets.QAction(MainWindow)
        self.actionMachinery.setCheckable(True)
        self.actionMachinery.setObjectName("actionMachinery")
        self.actionMinimalist = QtWidgets.QAction(MainWindow)
        self.actionMinimalist.setCheckable(True)
        self.actionMinimalist.setObjectName("actionMinimalist")
        self.actionNightMapping = QtWidgets.QAction(MainWindow)
        self.actionNightMapping.setCheckable(True)
        self.actionNightMapping.setObjectName("actionNightMapping")
        self.actionWombat = QtWidgets.QAction(MainWindow)
        self.actionWombat.setCheckable(True)
        self.actionWombat.setObjectName("actionWombat")
        self.menuFile.addAction(self.actionNewFile)
        self.menuFile.addAction(self.actionOpenFile)
        self.menuFile.addAction(self.actionSaveFile)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExportReport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuMethods.addAction(self.actionFiniteDifferenceMethod)
        self.menuMethods.addAction(self.actionLinearAccelerationMethod)
        self.menuConfigurations.addAction(self.menuMethods.menuAction())
        self.menuConfigurations.addAction(self.actionStepSize)
        self.menuConfigurations.addAction(self.actionBoundaryConditions)
        self.menuConfigurations.addAction(self.actionStructureDamping)
        self.menuConfigurations.addAction(self.actionFluidParameters)
        self.menuConfigurations.addAction(self.actionDMFSettings)
        self.menuRun.addAction(self.actionRunDynamicResponse)
        self.menuRun.addAction(self.actionDynamicMagnificationFactor)
        self.menuRun.addAction(self.actionOptimization)
        self.menuTheme.addAction(self.actionBasicWhite)
        self.menuTheme.addSeparator()
        self.menuTheme.addAction(self.actionAqua)
        self.menuTheme.addAction(self.actionBlueGlass)
        self.menuTheme.addAction(self.actionDarcula)
        self.menuTheme.addAction(self.actionDark)
        self.menuTheme.addAction(self.actionDarkBlue)
        self.menuTheme.addAction(self.actionDarkBlueFreeCAD)
        self.menuTheme.addAction(self.actionDarkGreen)
        self.menuTheme.addAction(self.actionDarkGreenFreeCAD)
        self.menuTheme.addAction(self.actionDarkOrange)
        self.menuTheme.addAction(self.actionDarkOrangeFreeCAD)
        self.menuTheme.addAction(self.actionLight)
        self.menuTheme.addAction(self.actionLightBlueFreeCAD)
        self.menuTheme.addAction(self.actionLightGreenFreeCAD)
        self.menuTheme.addAction(self.actionLightOrangeFreeCAD)
        self.menuTheme.addAction(self.actionMachinery)
        self.menuTheme.addAction(self.actionMinimalist)
        self.menuTheme.addAction(self.actionNightMapping)
        self.menuTheme.addAction(self.actionWombat)
        self.menuWindow.addAction(self.menuTheme.menuAction())
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.actionMaximize)
        self.menuWindow.addAction(self.actionFullScreen)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionDevelopmentTool)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuConfigurations.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tlcdStackedWidget.setCurrentIndex(0)
        self.excitationStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dynapy TLCD Analyser"))
        self.label.setText(_translate("MainWindow", "Story Number"))
        self.storyNumberComboBox.setItemText(0, _translate("MainWindow", "1"))
        self.label_2.setText(_translate("MainWindow", "Story Mass: (tons)"))
        self.storyMassLineEdit.setPlaceholderText(_translate("MainWindow", "10"))
        self.label_3.setText(_translate("MainWindow", "Story Height: (m)"))
        self.storyHeightLineEdit.setPlaceholderText(_translate("MainWindow", "3"))
        self.label_4.setText(_translate("MainWindow", "Column Width: (m)"))
        self.columnWidthLineEdit.setPlaceholderText(_translate("MainWindow", "0.35"))
        self.label_5.setText(_translate("MainWindow", "Column Depth: (m)"))
        self.columnDepthLineEdit.setPlaceholderText(_translate("MainWindow", "0.35"))
        self.label_6.setText(_translate("MainWindow", "Elasticity Module: (GPa)"))
        self.elasticityModuleLineEdit.setPlaceholderText(_translate("MainWindow", "25"))
        self.label_7.setText(_translate("MainWindow", "Support Type: "))
        self.supportTypeComboBox.setItemText(0, _translate("MainWindow", "Fix-Fix"))
        self.supportTypeComboBox.setItemText(1, _translate("MainWindow", "Fix-Pin"))
        self.supportTypeComboBox.setItemText(2, _translate("MainWindow", "Pin-Fix"))
        self.supportTypeComboBox.setItemText(3, _translate("MainWindow", "Pin-Pin"))
        self.addStoryBtn.setText(_translate("MainWindow", "Add Story"))
        self.removeStoryBtn.setText(_translate("MainWindow", "Remove Story"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Structure"))
        self.confirmTlcdBtn.setText(_translate("MainWindow", "Confirm TLCD"))
        self.label_8.setText(_translate("MainWindow", "TLCD Model"))
        self.tlcdModelComboBox.setItemText(0, _translate("MainWindow", "None"))
        self.tlcdModelComboBox.setItemText(1, _translate("MainWindow", "Basic TLCD"))
        self.tlcdModelComboBox.setItemText(2, _translate("MainWindow", "Pressurized TLCD"))
        self.label_9.setText(_translate("MainWindow", "No info needed."))
        self.label_12.setText(_translate("MainWindow", "Width: (cm)"))
        self.diameterSimpleTlcdLineEdit.setPlaceholderText(_translate("MainWindow", "30"))
        self.widthSimpleTlcdLineEdit.setPlaceholderText(_translate("MainWindow", "1000"))
        self.label_10.setText(_translate("MainWindow", "Diameter: (cm)"))
        self.label_11.setText(_translate("MainWindow", "Water Level: (cm)"))
        self.waterLevelSimpleTlcdLineEdit.setPlaceholderText(_translate("MainWindow", "100"))
        self.label_25.setText(_translate("MainWindow", "Amount"))
        self.amountSimpleTlcdLineEdit.setPlaceholderText(_translate("MainWindow", "1"))
        self.diameterPressureTlcdLineEdit.setPlaceholderText(_translate("MainWindow", "30"))
        self.label_19.setText(_translate("MainWindow", "Diameter: (cm)"))
        self.label_22.setText(_translate("MainWindow", "Water Level: (cm)"))
        self.label_24.setText(_translate("MainWindow", "Gas Height(cm)"))
        self.waterLevelPressureTlcdLineEdit.setPlaceholderText(_translate("MainWindow", "100"))
        self.widthPressureTlcdLineEdit.setPlaceholderText(_translate("MainWindow", "1000"))
        self.label_21.setText(_translate("MainWindow", "Width: (cm)"))
        self.gasHeightPressureTlcdLineEdit.setPlaceholderText(_translate("MainWindow", "40"))
        self.gasPressurePressureTlcdLineEdit.setPlaceholderText(_translate("MainWindow", "3"))
        self.label_23.setText(_translate("MainWindow", "Gas Pressure (atm)"))
        self.label_26.setText(_translate("MainWindow", "Amount"))
        self.amountPressureTlcdLineEdit.setPlaceholderText(_translate("MainWindow", "1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "TLCD"))
        self.excitationTypeComboBox.setItemText(0, _translate("MainWindow", "Sine Wave"))
        self.excitationTypeComboBox.setItemText(1, _translate("MainWindow", "General Excitation"))
        self.confirmExcitationButton.setText(_translate("MainWindow", "Confirm Excitation"))
        self.label_14.setText(_translate("MainWindow", "Amplitude: (m/s²)"))
        self.sineAmplitudeLineEdit.setPlaceholderText(_translate("MainWindow", "5"))
        self.sineFrequencyLabel.setText(_translate("MainWindow", "Frequency: (rad/s)"))
        self.sineFrequencyLineEdit.setPlaceholderText(_translate("MainWindow", "30"))
        self.sineFrequencyRatioCheckBox.setText(_translate("MainWindow", "Use Frequency Ratio"))
        self.label_16.setText(_translate("MainWindow", "Excitation Duration: (s)"))
        self.sineExcitationDurationLineEdit.setPlaceholderText(_translate("MainWindow", "5"))
        self.label_17.setText(_translate("MainWindow", "Analysis Duration: (s)"))
        self.sineAnalysisDurationLineEdit.setPlaceholderText(_translate("MainWindow", "5"))
        self.importExcitationButton.setText(_translate("MainWindow", "Import Loading File"))
        self.generateExcitationButton.setText(_translate("MainWindow", "Generate Loading File"))
        self.label_18.setText(_translate("MainWindow", "File: "))
        self.label_13.setText(_translate("MainWindow", "Excitation Type"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Excitation"))
        self.reportTextBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">Report not yet generated.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">Fill all the input fields and and Run the calculations to generate report.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Report"))
        self.groupBox.setTitle(_translate("MainWindow", "List of Degrees of Freedom Available"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Degrees of Freedom to Plot"))
        self.addToPlotButton.setText(_translate("MainWindow", "+"))
        self.removeFromPlotButton.setText(_translate("MainWindow", "-"))
        self.label_20.setText(_translate("MainWindow", "Plot Type:"))
        self.plotButton.setText(_translate("MainWindow", "Plot"))
        self.plotTypeComboBox.setItemText(0, _translate("MainWindow", "Displacement Vs. Time"))
        self.plotTypeComboBox.setItemText(1, _translate("MainWindow", "Velocity Vs. Time"))
        self.plotTypeComboBox.setItemText(2, _translate("MainWindow", "Acceleration Vs. Time"))
        self.plotTypeComboBox.setItemText(3, _translate("MainWindow", "Displacement Vs. Velocity"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Dynamic Response"))
        self.groupBox_3.setTitle(_translate("MainWindow", "List of Degrees of Freedom Available"))
        self.addToDMFPlot.setText(_translate("MainWindow", "+"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Degrees of Freedom to Plot"))
        self.removeFromDMFPlot.setText(_translate("MainWindow", "-"))
        self.label_15.setText(_translate("MainWindow", "Plot Type:"))
        self.dmfPlotTypeComboBox.setItemText(0, _translate("MainWindow", "DMF Vs Excitation Frequency"))
        self.dmfPlotTypeComboBox.setItemText(1, _translate("MainWindow", "Max. Displacement Vs. Excitation Frequency"))
        self.dmfPlotButton.setText(_translate("MainWindow", "Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Frequency Analysis"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuConfigurations.setTitle(_translate("MainWindow", "Configurations"))
        self.menuMethods.setTitle(_translate("MainWindow", "Methods"))
        self.menuRun.setTitle(_translate("MainWindow", "Run"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.menuTheme.setTitle(_translate("MainWindow", "Theme"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNewFile.setText(_translate("MainWindow", "New"))
        self.actionNewFile.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpenFile.setText(_translate("MainWindow", "Open..."))
        self.actionOpenFile.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSaveFile.setText(_translate("MainWindow", "Save"))
        self.actionSaveFile.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save as..."))
        self.actionSaveAs.setShortcut(_translate("MainWindow", "Ctrl+Alt+S"))
        self.actionExportReport.setText(_translate("MainWindow", "Export Report..."))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionFiniteDifferenceMethod.setText(_translate("MainWindow", "Finite Differences Method"))
        self.actionStepSize.setText(_translate("MainWindow", "Step Size..."))
        self.actionBoundaryConditions.setText(_translate("MainWindow", "Boundary Conditions..."))
        self.actionStructureDamping.setText(_translate("MainWindow", "Structure Damping..."))
        self.actionFluidParameters.setText(_translate("MainWindow", "Fluid Parameters..."))
        self.actionLinearAccelerationMethod.setText(_translate("MainWindow", "Linear Acceleration Method"))
        self.actionRunDynamicResponse.setText(_translate("MainWindow", "Dynamic Response"))
        self.actionRunDynamicResponse.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionDynamicMagnificationFactor.setText(_translate("MainWindow", "Dynamic Magnification Factor"))
        self.actionDynamicMagnificationFactor.setShortcut(_translate("MainWindow", "Ctrl+Alt+R"))
        self.actionOptimization.setText(_translate("MainWindow", "Optimization"))
        self.actionMaximize.setText(_translate("MainWindow", "Maximize"))
        self.actionFullScreen.setText(_translate("MainWindow", "Full Screen"))
        self.actionFullScreen.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "F1"))
        self.actionDevelopmentTool.setText(_translate("MainWindow", "Development Tool"))
        self.actionDevelopmentTool.setShortcut(_translate("MainWindow", "F10"))
        self.actionBasicWhite.setText(_translate("MainWindow", "Basic White"))
        self.actionDarkOrange.setText(_translate("MainWindow", "Dark Orange"))
        self.actionDarkGreen.setText(_translate("MainWindow", "Dark Green"))
        self.actionAqua.setText(_translate("MainWindow", "Aqua"))
        self.actionDarkBlue.setText(_translate("MainWindow", "Dark Blue"))
        self.actionDMFSettings.setText(_translate("MainWindow", "DMF Settings..."))
        self.actionDarcula.setText(_translate("MainWindow", "Darcula"))
        self.actionBlueGlass.setText(_translate("MainWindow", "Blue Glass"))
        self.actionDark.setText(_translate("MainWindow", "Dark"))
        self.actionDarkBlueFreeCAD.setText(_translate("MainWindow", "Dark Blue (FreeCAD)"))
        self.actionDarkGreenFreeCAD.setText(_translate("MainWindow", "Dark Green (FreeCAD)"))
        self.actionDarkOrangeFreeCAD.setText(_translate("MainWindow", "Dark Orange (FreeCAD)"))
        self.actionLight.setText(_translate("MainWindow", "Light"))
        self.actionLightBlueFreeCAD.setText(_translate("MainWindow", "Light Blue (FreeCAD)"))
        self.actionLightGreenFreeCAD.setText(_translate("MainWindow", "Light Green (FreeCAD)"))
        self.actionLightOrangeFreeCAD.setText(_translate("MainWindow", "Light Orange (FreeCAD)"))
        self.actionMachinery.setText(_translate("MainWindow", "Machinery"))
        self.actionMinimalist.setText(_translate("MainWindow", "Minimalist"))
        self.actionNightMapping.setText(_translate("MainWindow", "Night Mapping"))
        self.actionWombat.setText(_translate("MainWindow", "Wombat"))

