# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowGUI.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(573, 478)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.storyNumberComboBox = QtWidgets.QComboBox(self.tab)
        self.storyNumberComboBox.setObjectName("storyNumberComboBox")
        self.storyNumberComboBox.addItem("")
        self.gridLayout_3.addWidget(self.storyNumberComboBox, 0, 1, 1, 1)
        self.supportTypeComboBox = QtWidgets.QComboBox(self.tab)
        self.supportTypeComboBox.setObjectName("supportTypeComboBox")
        self.supportTypeComboBox.addItem("")
        self.supportTypeComboBox.addItem("")
        self.supportTypeComboBox.addItem("")
        self.supportTypeComboBox.addItem("")
        self.gridLayout_3.addWidget(self.supportTypeComboBox, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 6, 0, 1, 1)
        self.storyMassLineEdit = QtWidgets.QLineEdit(self.tab)
        self.storyMassLineEdit.setObjectName("storyMassLineEdit")
        self.gridLayout_3.addWidget(self.storyMassLineEdit, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.columnWidthLineEdit = QtWidgets.QLineEdit(self.tab)
        self.columnWidthLineEdit.setObjectName("columnWidthLineEdit")
        self.gridLayout_3.addWidget(self.columnWidthLineEdit, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 4, 0, 1, 1)
        self.elasticityModuleLineEdit = QtWidgets.QLineEdit(self.tab)
        self.elasticityModuleLineEdit.setObjectName("elasticityModuleLineEdit")
        self.gridLayout_3.addWidget(self.elasticityModuleLineEdit, 5, 1, 1, 1)
        self.addStoryBtn = QtWidgets.QPushButton(self.tab)
        self.addStoryBtn.setObjectName("addStoryBtn")
        self.gridLayout_3.addWidget(self.addStoryBtn, 7, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 5, 0, 1, 1)
        self.storyHeightLineEdit = QtWidgets.QLineEdit(self.tab)
        self.storyHeightLineEdit.setObjectName("storyHeightLineEdit")
        self.gridLayout_3.addWidget(self.storyHeightLineEdit, 2, 1, 1, 1)
        self.columnDepthLineEdit = QtWidgets.QLineEdit(self.tab)
        self.columnDepthLineEdit.setObjectName("columnDepthLineEdit")
        self.gridLayout_3.addWidget(self.columnDepthLineEdit, 4, 1, 1, 1)
        self.removeStoryBtn = QtWidgets.QPushButton(self.tab)
        self.removeStoryBtn.setObjectName("removeStoryBtn")
        self.gridLayout_3.addWidget(self.removeStoryBtn, 8, 0, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.structureWidget = QtWidgets.QWidget(self.tab)
        self.structureWidget.setObjectName("structureWidget")
        self.horizontalLayout.addWidget(self.structureWidget)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tlcdModelComboBox = QtWidgets.QComboBox(self.tab_2)
        self.tlcdModelComboBox.setObjectName("tlcdModelComboBox")
        self.tlcdModelComboBox.addItem("")
        self.tlcdModelComboBox.addItem("")
        self.gridLayout_4.addWidget(self.tlcdModelComboBox, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.confirmTlcdBtn = QtWidgets.QPushButton(self.tab_2)
        self.confirmTlcdBtn.setObjectName("confirmTlcdBtn")
        self.gridLayout_4.addWidget(self.confirmTlcdBtn, 2, 0, 1, 2)
        self.tlcdStackedWidget = QtWidgets.QStackedWidget(self.tab_2)
        self.tlcdStackedWidget.setObjectName("tlcdStackedWidget")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_9 = QtWidgets.QLabel(self.page_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.tlcdStackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_12 = QtWidgets.QLabel(self.page_6)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 2, 0, 1, 1)
        self.diameterSimpleTlcdLineEdit = QtWidgets.QLineEdit(self.page_6)
        self.diameterSimpleTlcdLineEdit.setObjectName("diameterSimpleTlcdLineEdit")
        self.gridLayout_7.addWidget(self.diameterSimpleTlcdLineEdit, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.page_6)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.page_6)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 1, 0, 1, 1)
        self.waterLevelSimpleTlcdLineEdit = QtWidgets.QLineEdit(self.page_6)
        self.waterLevelSimpleTlcdLineEdit.setObjectName("waterLevelSimpleTlcdLineEdit")
        self.gridLayout_7.addWidget(self.waterLevelSimpleTlcdLineEdit, 1, 1, 1, 1)
        self.widthSimpleTlcdLineEdit = QtWidgets.QLineEdit(self.page_6)
        self.widthSimpleTlcdLineEdit.setObjectName("widthSimpleTlcdLineEdit")
        self.gridLayout_7.addWidget(self.widthSimpleTlcdLineEdit, 2, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.tlcdStackedWidget.addWidget(self.page_6)
        self.gridLayout_4.addWidget(self.tlcdStackedWidget, 1, 0, 1, 2)
        self.horizontalLayout_3.addLayout(self.gridLayout_4)
        self.tlcdWidget = QtWidgets.QWidget(self.tab_2)
        self.tlcdWidget.setObjectName("tlcdWidget")
        self.horizontalLayout_3.addWidget(self.tlcdWidget)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.excitationWidget = QtWidgets.QWidget(self.tab_3)
        self.excitationWidget.setObjectName("excitationWidget")
        self.gridLayout_10.addWidget(self.excitationWidget, 0, 1, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_9.addWidget(self.label_13, 0, 0, 1, 1)
        self.excitationTypeComboBox = QtWidgets.QComboBox(self.tab_3)
        self.excitationTypeComboBox.setObjectName("excitationTypeComboBox")
        self.excitationTypeComboBox.addItem("")
        self.excitationTypeComboBox.addItem("")
        self.gridLayout_9.addWidget(self.excitationTypeComboBox, 0, 1, 1, 1)
        self.confirmExcitationButton = QtWidgets.QPushButton(self.tab_3)
        self.confirmExcitationButton.setObjectName("confirmExcitationButton")
        self.gridLayout_9.addWidget(self.confirmExcitationButton, 2, 0, 1, 2)
        self.excitationStackedWidget = QtWidgets.QStackedWidget(self.tab_3)
        self.excitationStackedWidget.setObjectName("excitationStackedWidget")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_14 = QtWidgets.QLabel(self.page_7)
        self.label_14.setObjectName("label_14")
        self.gridLayout_12.addWidget(self.label_14, 0, 0, 1, 1)
        self.sineFrequencyLabel = QtWidgets.QLabel(self.page_7)
        self.sineFrequencyLabel.setObjectName("sineFrequencyLabel")
        self.gridLayout_12.addWidget(self.sineFrequencyLabel, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.page_7)
        self.label_16.setObjectName("label_16")
        self.gridLayout_12.addWidget(self.label_16, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.page_7)
        self.label_17.setObjectName("label_17")
        self.gridLayout_12.addWidget(self.label_17, 3, 0, 1, 1)
        self.sineAmplitudeLineEdit = QtWidgets.QLineEdit(self.page_7)
        self.sineAmplitudeLineEdit.setObjectName("sineAmplitudeLineEdit")
        self.gridLayout_12.addWidget(self.sineAmplitudeLineEdit, 0, 1, 1, 1)
        self.sineFrequencyLineEdit = QtWidgets.QLineEdit(self.page_7)
        self.sineFrequencyLineEdit.setObjectName("sineFrequencyLineEdit")
        self.gridLayout_12.addWidget(self.sineFrequencyLineEdit, 1, 1, 1, 1)
        self.sineExcitationDurationLineEdit = QtWidgets.QLineEdit(self.page_7)
        self.sineExcitationDurationLineEdit.setObjectName("sineExcitationDurationLineEdit")
        self.gridLayout_12.addWidget(self.sineExcitationDurationLineEdit, 2, 1, 1, 1)
        self.sineAnalysisDurationLineEdit = QtWidgets.QLineEdit(self.page_7)
        self.sineAnalysisDurationLineEdit.setObjectName("sineAnalysisDurationLineEdit")
        self.gridLayout_12.addWidget(self.sineAnalysisDurationLineEdit, 3, 1, 1, 1)
        self.sineFrequencyRatioCheckBox = QtWidgets.QCheckBox(self.page_7)
        self.sineFrequencyRatioCheckBox.setChecked(True)
        self.sineFrequencyRatioCheckBox.setObjectName("sineFrequencyRatioCheckBox")
        self.gridLayout_12.addWidget(self.sineFrequencyRatioCheckBox, 1, 2, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.excitationStackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.page_8)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_18 = QtWidgets.QLabel(self.page_8)
        self.label_18.setObjectName("label_18")
        self.gridLayout_14.addWidget(self.label_18, 0, 0, 1, 1)
        self.excitationFileLineEdit = QtWidgets.QLineEdit(self.page_8)
        self.excitationFileLineEdit.setObjectName("excitationFileLineEdit")
        self.gridLayout_14.addWidget(self.excitationFileLineEdit, 0, 1, 1, 1)
        self.generateExcitationButton = QtWidgets.QPushButton(self.page_8)
        self.generateExcitationButton.setObjectName("generateExcitationButton")
        self.gridLayout_14.addWidget(self.generateExcitationButton, 1, 1, 1, 1)
        self.importExcitationButton = QtWidgets.QPushButton(self.page_8)
        self.importExcitationButton.setObjectName("importExcitationButton")
        self.gridLayout_14.addWidget(self.importExcitationButton, 1, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.excitationStackedWidget.addWidget(self.page_8)
        self.gridLayout_9.addWidget(self.excitationStackedWidget, 1, 0, 1, 2)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.reportTextBrowser = QtWidgets.QTextBrowser(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.reportTextBrowser.setFont(font)
        self.reportTextBrowser.setObjectName("reportTextBrowser")
        self.gridLayout_16.addWidget(self.reportTextBrowser, 0, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.list2 = QtWidgets.QListWidget(self.groupBox_2)
        self.list2.setObjectName("list2")
        self.gridLayout_21.addWidget(self.list2, 0, 0, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_21, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox_2, 0, 5, 3, 2)
        self.removeFromPlotButton = QtWidgets.QPushButton(self.tab_5)
        self.removeFromPlotButton.setObjectName("removeFromPlotButton")
        self.gridLayout_18.addWidget(self.removeFromPlotButton, 1, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem, 2, 4, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_5)
        self.label_20.setObjectName("label_20")
        self.gridLayout_18.addWidget(self.label_20, 3, 0, 1, 1)
        self.plotButton = QtWidgets.QPushButton(self.tab_5)
        self.plotButton.setObjectName("plotButton")
        self.gridLayout_18.addWidget(self.plotButton, 3, 6, 1, 1)
        self.addToPlotButton = QtWidgets.QPushButton(self.tab_5)
        self.addToPlotButton.setObjectName("addToPlotButton")
        self.gridLayout_18.addWidget(self.addToPlotButton, 0, 4, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.list1 = QtWidgets.QListWidget(self.groupBox)
        self.list1.setObjectName("list1")
        self.gridLayout_19.addWidget(self.list1, 0, 0, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_19, 0, 0, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox, 0, 0, 3, 4)
        self.plotTypeComboBox = QtWidgets.QComboBox(self.tab_5)
        self.plotTypeComboBox.setObjectName("plotTypeComboBox")
        self.plotTypeComboBox.addItem("")
        self.plotTypeComboBox.addItem("")
        self.plotTypeComboBox.addItem("")
        self.plotTypeComboBox.addItem("")
        self.gridLayout_18.addWidget(self.plotTypeComboBox, 3, 1, 1, 3)
        self.horizontalLayout_5.addLayout(self.gridLayout_18)
        self.dynRespWidget = QtWidgets.QWidget(self.tab_5)
        self.dynRespWidget.setObjectName("dynRespWidget")
        self.horizontalLayout_5.addWidget(self.dynRespWidget)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout_25 = QtWidgets.QGridLayout()
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.addToDMFPlot = QtWidgets.QPushButton(self.tab_6)
        self.addToDMFPlot.setObjectName("addToDMFPlot")
        self.gridLayout_25.addWidget(self.addToDMFPlot, 1, 2, 1, 1)
        self.removeFromDMFPlot = QtWidgets.QPushButton(self.tab_6)
        self.removeFromDMFPlot.setObjectName("removeFromDMFPlot")
        self.gridLayout_25.addWidget(self.removeFromDMFPlot, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_25.addItem(spacerItem1, 3, 2, 1, 1)
        self.dmfPlotTypeComboBox = QtWidgets.QComboBox(self.tab_6)
        self.dmfPlotTypeComboBox.setObjectName("dmfPlotTypeComboBox")
        self.dmfPlotTypeComboBox.addItem("")
        self.dmfPlotTypeComboBox.addItem("")
        self.gridLayout_25.addWidget(self.dmfPlotTypeComboBox, 4, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_6)
        self.label_15.setObjectName("label_15")
        self.gridLayout_25.addWidget(self.label_15, 4, 0, 1, 1)
        self.dmfPlotButton = QtWidgets.QPushButton(self.tab_6)
        self.dmfPlotButton.setObjectName("dmfPlotButton")
        self.gridLayout_25.addWidget(self.dmfPlotButton, 4, 4, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.gridLayout_26 = QtWidgets.QGridLayout()
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.list3 = QtWidgets.QListWidget(self.groupBox_3)
        self.list3.setObjectName("list3")
        self.gridLayout_26.addWidget(self.list3, 0, 0, 1, 1)
        self.gridLayout_27.addLayout(self.gridLayout_26, 0, 0, 1, 1)
        self.gridLayout_25.addWidget(self.groupBox_3, 1, 0, 3, 2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.gridLayout_28 = QtWidgets.QGridLayout()
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.list4 = QtWidgets.QListWidget(self.groupBox_4)
        self.list4.setObjectName("list4")
        self.gridLayout_28.addWidget(self.list4, 0, 0, 1, 1)
        self.gridLayout_29.addLayout(self.gridLayout_28, 0, 0, 1, 1)
        self.gridLayout_25.addWidget(self.groupBox_4, 1, 3, 3, 2)
        self.dmfProgressBar = QtWidgets.QProgressBar(self.tab_6)
        self.dmfProgressBar.setProperty("value", 0)
        self.dmfProgressBar.setObjectName("dmfProgressBar")
        self.gridLayout_25.addWidget(self.dmfProgressBar, 0, 0, 1, 5)
        self.horizontalLayout_7.addLayout(self.gridLayout_25)
        self.dmfWidget = QtWidgets.QWidget(self.tab_6)
        self.dmfWidget.setObjectName("dmfWidget")
        self.horizontalLayout_7.addWidget(self.dmfWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab_7)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_23.addWidget(self.textBrowser_2, 0, 0, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_23, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_7, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 573, 21))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuConfigura_es = QtWidgets.QMenu(self.menubar)
        self.menuConfigura_es.setObjectName("menuConfigura_es")
        self.menuM_todos = QtWidgets.QMenu(self.menuConfigura_es)
        self.menuM_todos.setObjectName("menuM_todos")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuTheme = QtWidgets.QMenu(self.menuWindow)
        self.menuTheme.setObjectName("menuTheme")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNewFile = QtWidgets.QAction(MainWindow)
        self.actionNewFile.setObjectName("actionNewFile")
        self.actionOpenFile = QtWidgets.QAction(MainWindow)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.actionSaveFile = QtWidgets.QAction(MainWindow)
        self.actionSaveFile.setObjectName("actionSaveFile")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionExportReport = QtWidgets.QAction(MainWindow)
        self.actionExportReport.setObjectName("actionExportReport")
        self.actionExportAnimation = QtWidgets.QAction(MainWindow)
        self.actionExportAnimation.setObjectName("actionExportAnimation")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionFiniteDifferenceMethod = QtWidgets.QAction(MainWindow)
        self.actionFiniteDifferenceMethod.setCheckable(True)
        self.actionFiniteDifferenceMethod.setChecked(True)
        self.actionFiniteDifferenceMethod.setObjectName("actionFiniteDifferenceMethod")
        self.actionStepSize = QtWidgets.QAction(MainWindow)
        self.actionStepSize.setObjectName("actionStepSize")
        self.actionBoundaryConditions = QtWidgets.QAction(MainWindow)
        self.actionBoundaryConditions.setObjectName("actionBoundaryConditions")
        self.actionStructureDamping = QtWidgets.QAction(MainWindow)
        self.actionStructureDamping.setObjectName("actionStructureDamping")
        self.actionFluidParameters = QtWidgets.QAction(MainWindow)
        self.actionFluidParameters.setObjectName("actionFluidParameters")
        self.actionLinearAccelerationMethod = QtWidgets.QAction(MainWindow)
        self.actionLinearAccelerationMethod.setCheckable(True)
        self.actionLinearAccelerationMethod.setObjectName("actionLinearAccelerationMethod")
        self.actionRunDynamicResponse = QtWidgets.QAction(MainWindow)
        self.actionRunDynamicResponse.setObjectName("actionRunDynamicResponse")
        self.actionDynamicMagnificationFactor = QtWidgets.QAction(MainWindow)
        self.actionDynamicMagnificationFactor.setObjectName("actionDynamicMagnificationFactor")
        self.actionOptimization = QtWidgets.QAction(MainWindow)
        self.actionOptimization.setObjectName("actionOptimization")
        self.actionAnimation = QtWidgets.QAction(MainWindow)
        self.actionAnimation.setObjectName("actionAnimation")
        self.actionMaximize = QtWidgets.QAction(MainWindow)
        self.actionMaximize.setObjectName("actionMaximize")
        self.actionFullScreen = QtWidgets.QAction(MainWindow)
        self.actionFullScreen.setObjectName("actionFullScreen")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDevelopmentTool = QtWidgets.QAction(MainWindow)
        self.actionDevelopmentTool.setObjectName("actionDevelopmentTool")
        self.actionBasicWhite = QtWidgets.QAction(MainWindow)
        self.actionBasicWhite.setCheckable(True)
        self.actionBasicWhite.setChecked(True)
        self.actionBasicWhite.setObjectName("actionBasicWhite")
        self.actionDarkOrange = QtWidgets.QAction(MainWindow)
        self.actionDarkOrange.setCheckable(True)
        self.actionDarkOrange.setObjectName("actionDarkOrange")
        self.actionDarkGreen = QtWidgets.QAction(MainWindow)
        self.actionDarkGreen.setCheckable(True)
        self.actionDarkGreen.setObjectName("actionDarkGreen")
        self.actionAqua = QtWidgets.QAction(MainWindow)
        self.actionAqua.setCheckable(True)
        self.actionAqua.setObjectName("actionAqua")
        self.actionDarkBlue = QtWidgets.QAction(MainWindow)
        self.actionDarkBlue.setCheckable(True)
        self.actionDarkBlue.setObjectName("actionDarkBlue")
        self.actionDMFSettings = QtWidgets.QAction(MainWindow)
        self.actionDMFSettings.setObjectName("actionDMFSettings")
        self.actionDarcula = QtWidgets.QAction(MainWindow)
        self.actionDarcula.setCheckable(True)
        self.actionDarcula.setObjectName("actionDarcula")
        self.menuArquivo.addAction(self.actionNewFile)
        self.menuArquivo.addAction(self.actionOpenFile)
        self.menuArquivo.addAction(self.actionSaveFile)
        self.menuArquivo.addAction(self.actionSaveAs)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionExportReport)
        self.menuArquivo.addAction(self.actionExportAnimation)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionQuit)
        self.menuM_todos.addAction(self.actionFiniteDifferenceMethod)
        self.menuM_todos.addAction(self.actionLinearAccelerationMethod)
        self.menuConfigura_es.addAction(self.menuM_todos.menuAction())
        self.menuConfigura_es.addAction(self.actionStepSize)
        self.menuConfigura_es.addAction(self.actionBoundaryConditions)
        self.menuConfigura_es.addAction(self.actionStructureDamping)
        self.menuConfigura_es.addAction(self.actionFluidParameters)
        self.menuConfigura_es.addAction(self.actionDMFSettings)
        self.menuRun.addAction(self.actionRunDynamicResponse)
        self.menuRun.addAction(self.actionDynamicMagnificationFactor)
        self.menuRun.addAction(self.actionOptimization)
        self.menuRun.addAction(self.actionAnimation)
        self.menuTheme.addAction(self.actionBasicWhite)
        self.menuTheme.addAction(self.actionAqua)
        self.menuTheme.addAction(self.actionDarkOrange)
        self.menuTheme.addAction(self.actionDarkGreen)
        self.menuTheme.addAction(self.actionDarkBlue)
        self.menuTheme.addAction(self.actionDarcula)
        self.menuWindow.addAction(self.menuTheme.menuAction())
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.actionMaximize)
        self.menuWindow.addAction(self.actionFullScreen)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionDevelopmentTool)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuConfigura_es.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tlcdStackedWidget.setCurrentIndex(0)
        self.excitationStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dynapy TLCD Analyser"))
        self.storyNumberComboBox.setItemText(0, _translate("MainWindow", "1"))
        self.supportTypeComboBox.setItemText(0, _translate("MainWindow", "Fix-Fix"))
        self.supportTypeComboBox.setItemText(1, _translate("MainWindow", "Fix-Pin"))
        self.supportTypeComboBox.setItemText(2, _translate("MainWindow", "Pin-Fix"))
        self.supportTypeComboBox.setItemText(3, _translate("MainWindow", "Pin-Pin"))
        self.label_4.setText(_translate("MainWindow", "Column Width: (m)"))
        self.label_7.setText(_translate("MainWindow", "Support Type: "))
        self.storyMassLineEdit.setPlaceholderText(_translate("MainWindow", "10"))
        self.label.setText(_translate("MainWindow", "Story Number"))
        self.columnWidthLineEdit.setPlaceholderText(_translate("MainWindow", "0.35"))
        self.label_2.setText(_translate("MainWindow", "Story Mass: (tons)"))
        self.label_5.setText(_translate("MainWindow", "Column Depth: (m)"))
        self.elasticityModuleLineEdit.setPlaceholderText(_translate("MainWindow", "25"))
        self.addStoryBtn.setText(_translate("MainWindow", "Add Story"))
        self.label_3.setText(_translate("MainWindow", "Story Height: (m)"))
        self.label_6.setText(_translate("MainWindow", "Elasticity Module: (GPa)"))
        self.storyHeightLineEdit.setPlaceholderText(_translate("MainWindow", "3"))
        self.columnDepthLineEdit.setPlaceholderText(_translate("MainWindow", "0.35"))
        self.removeStoryBtn.setText(_translate("MainWindow", "Remove Story"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Structure"))
        self.tlcdModelComboBox.setItemText(0, _translate("MainWindow", "None"))
        self.tlcdModelComboBox.setItemText(1, _translate("MainWindow", "Basic TLCD"))
        self.label_8.setText(_translate("MainWindow", "TLCD Model"))
        self.confirmTlcdBtn.setText(_translate("MainWindow", "Confirm TLCD"))
        self.label_9.setText(_translate("MainWindow", "No info needed."))
        self.label_12.setText(_translate("MainWindow", "Width: (cm)"))
        self.diameterSimpleTlcdLineEdit.setPlaceholderText(_translate("MainWindow", "30"))
        self.label_10.setText(_translate("MainWindow", "Diameter: (cm)"))
        self.label_11.setText(_translate("MainWindow", "Water Level: (cm)"))
        self.waterLevelSimpleTlcdLineEdit.setPlaceholderText(_translate("MainWindow", "100"))
        self.widthSimpleTlcdLineEdit.setPlaceholderText(_translate("MainWindow", "1000"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "TLCD"))
        self.label_13.setText(_translate("MainWindow", "Excitation Type"))
        self.excitationTypeComboBox.setItemText(0, _translate("MainWindow", "Sine Wave"))
        self.excitationTypeComboBox.setItemText(1, _translate("MainWindow", "General Excitation"))
        self.confirmExcitationButton.setText(_translate("MainWindow", "Confirm Excitation"))
        self.label_14.setText(_translate("MainWindow", "Amplitude: (m/s²)"))
        self.sineFrequencyLabel.setText(_translate("MainWindow", "Frequency: (rad/s)"))
        self.label_16.setText(_translate("MainWindow", "Excitation Duration: (s)"))
        self.label_17.setText(_translate("MainWindow", "Analysis Duration: (s)"))
        self.sineAmplitudeLineEdit.setPlaceholderText(_translate("MainWindow", "5"))
        self.sineFrequencyLineEdit.setPlaceholderText(_translate("MainWindow", "0.9"))
        self.sineExcitationDurationLineEdit.setPlaceholderText(_translate("MainWindow", "5"))
        self.sineAnalysisDurationLineEdit.setPlaceholderText(_translate("MainWindow", "5"))
        self.sineFrequencyRatioCheckBox.setText(_translate("MainWindow", "Use Frequency Ratio"))
        self.label_18.setText(_translate("MainWindow", "File: "))
        self.generateExcitationButton.setText(_translate("MainWindow", "Generate Loading File"))
        self.importExcitationButton.setText(_translate("MainWindow", "Import Loading File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Excitation"))
        self.reportTextBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">Report not yet generated.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">Fill all the input fields and and Run the calculations to generate report.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Report"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Degrees of Freedom to Plot"))
        self.removeFromPlotButton.setText(_translate("MainWindow", "-"))
        self.label_20.setText(_translate("MainWindow", "Plot Type:"))
        self.plotButton.setText(_translate("MainWindow", "Plot"))
        self.addToPlotButton.setText(_translate("MainWindow", "+"))
        self.groupBox.setTitle(_translate("MainWindow", "List of Degrees of Freedom Available"))
        self.plotTypeComboBox.setItemText(0, _translate("MainWindow", "Displacement Vs. Time"))
        self.plotTypeComboBox.setItemText(1, _translate("MainWindow", "Velocity Vs. Time"))
        self.plotTypeComboBox.setItemText(2, _translate("MainWindow", "Acceleration Vs. Time"))
        self.plotTypeComboBox.setItemText(3, _translate("MainWindow", "Displacement Vs. Velocity"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Dynamic Response"))
        self.addToDMFPlot.setText(_translate("MainWindow", "+"))
        self.removeFromDMFPlot.setText(_translate("MainWindow", "-"))
        self.dmfPlotTypeComboBox.setItemText(0, _translate("MainWindow", "DMF Vs Excitation Frequency"))
        self.dmfPlotTypeComboBox.setItemText(1, _translate("MainWindow", "Max. Displacement Vs. Excitation Frequency"))
        self.label_15.setText(_translate("MainWindow", "Plot Type:"))
        self.dmfPlotButton.setText(_translate("MainWindow", "Plot"))
        self.groupBox_3.setTitle(_translate("MainWindow", "List of Degrees of Freedom Available"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Degrees of Freedom to Plot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "DMF(r)"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">NOT IMPLEMENTED YET!</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Animation"))
        self.menuArquivo.setTitle(_translate("MainWindow", "File"))
        self.menuConfigura_es.setTitle(_translate("MainWindow", "Configurations"))
        self.menuM_todos.setTitle(_translate("MainWindow", "Methods"))
        self.menuRun.setTitle(_translate("MainWindow", "Run"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.menuTheme.setTitle(_translate("MainWindow", "Theme"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNewFile.setText(_translate("MainWindow", "New"))
        self.actionNewFile.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpenFile.setText(_translate("MainWindow", "Open..."))
        self.actionOpenFile.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSaveFile.setText(_translate("MainWindow", "Save"))
        self.actionSaveFile.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save as..."))
        self.actionSaveAs.setShortcut(_translate("MainWindow", "Ctrl+Alt+S"))
        self.actionExportReport.setText(_translate("MainWindow", "Export Report..."))
        self.actionExportAnimation.setText(_translate("MainWindow", "Export Animation..."))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionFiniteDifferenceMethod.setText(_translate("MainWindow", "Finite Differences Method"))
        self.actionStepSize.setText(_translate("MainWindow", "Step Size..."))
        self.actionBoundaryConditions.setText(_translate("MainWindow", "Boundary Conditions..."))
        self.actionStructureDamping.setText(_translate("MainWindow", "Structure Damping..."))
        self.actionFluidParameters.setText(_translate("MainWindow", "Fluid Parameters..."))
        self.actionLinearAccelerationMethod.setText(_translate("MainWindow", "Linear Acceleration Method"))
        self.actionRunDynamicResponse.setText(_translate("MainWindow", "Dynamic Response"))
        self.actionRunDynamicResponse.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionDynamicMagnificationFactor.setText(_translate("MainWindow", "Dynamic Magnification Factor"))
        self.actionDynamicMagnificationFactor.setShortcut(_translate("MainWindow", "Ctrl+Alt+R"))
        self.actionOptimization.setText(_translate("MainWindow", "Optimization"))
        self.actionAnimation.setText(_translate("MainWindow", "Animation"))
        self.actionMaximize.setText(_translate("MainWindow", "Maximize"))
        self.actionFullScreen.setText(_translate("MainWindow", "Full Screen"))
        self.actionFullScreen.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "F1"))
        self.actionDevelopmentTool.setText(_translate("MainWindow", "Development Tool"))
        self.actionDevelopmentTool.setShortcut(_translate("MainWindow", "F10"))
        self.actionBasicWhite.setText(_translate("MainWindow", "Basic White"))
        self.actionDarkOrange.setText(_translate("MainWindow", "Dark Orange"))
        self.actionDarkGreen.setText(_translate("MainWindow", "Dark Green"))
        self.actionAqua.setText(_translate("MainWindow", "Aqua"))
        self.actionDarkBlue.setText(_translate("MainWindow", "Dark Blue"))
        self.actionDMFSettings.setText(_translate("MainWindow", "DMF Settings..."))
        self.actionDarcula.setText(_translate("MainWindow", "Darcula"))

